const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
let state = {config:{server:'http://localhost:8080',token:'test',enabled:true,excluded:'private.example'},queue:[]};
let response = {ok:false,status:503};
const api = {storage:{local:{get:async()=>structuredClone(state),set:async values=>Object.assign(state,structuredClone(values))}},alarms:{create(){},onAlarm:{addListener(){}}},history:{onVisited:{addListener(){}}},runtime:{id:'test',onMessage:{addListener(){}}}};
const context = vm.createContext({chrome:api,URL,AbortSignal,crypto:require('node:crypto').webcrypto,fetch:async()=>response});
vm.runInContext(fs.readFileSync('extensions/chrome/background.js','utf8'),context);
(async()=>{
 const visit={event_id:'1',url:'https://example.com/page',title:'Page',visited_at:new Date().toISOString()};
 context.visits=[visit,visit,{...visit,event_id:'2',url:'https://private.example/secret'},{...visit,event_id:'3',url:'file:///private'},{...visit,event_id:'4',url:'http://localhost:8080/devices'}];
 await vm.runInContext('enqueue(visits)',context);
 assert.equal(state.queue.length,1);
 await assert.rejects(vm.runInContext('flush()',context));
 assert.equal(state.queue.length,1);
 response={ok:true,json:async()=>({accepted:1})};
 await vm.runInContext('flush()',context);
 assert.equal(state.queue.length,0);
 state.config.enabled=false;
 await vm.runInContext('enqueue(visits)',context);
 assert.equal(state.queue.length,0);
 state.config.enabled=true;
 state.importState={start:1000,end:4000,windows:[[2000,4000]],message:'Started'};
 api.history.search=async()=>[{url:'https://example.com/history',title:'History'}];
 api.history.getVisits=async()=>[{visitId:'older',visitTime:1500,isLocal:true},{visitId:'synced',visitTime:2500,isLocal:false},{visitId:'outside',visitTime:500,isLocal:true}];
 await vm.runInContext('importStep()',context);
 assert.equal(state.queue.length,1);
 assert.equal(state.queue[0].event_id,'chrome:older');
 assert.equal(state.importState.message,'Complete');
 console.log('Add-on import, queue, exclusions, pause, retry and acknowledgement tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
