const api = globalThis.browser || chrome;
let serial = Promise.resolve();
function locked(fn) { const next=serial.then(fn); serial=next.catch(()=>{}); return next; }
function allowed(url, config) { try { if(url.length>8192) return false; const u=new URL(url); return ['http:','https:'].includes(u.protocol) && !u.username && !u.password && u.origin!==config.server && !(config.excluded||'').split(',').map(x=>x.trim()).filter(Boolean).some(x=>u.hostname===x || u.hostname.endsWith('.'+x)); } catch { return false; } }
async function enqueue(visits) { const {config,queue=[]}=await api.storage.local.get(['config','queue']); if(!config?.enabled) return; const ids=new Set(queue.map(x=>x.event_id)); const fresh=visits.filter(x=>{if(!allowed(x.url,config)||ids.has(x.event_id)) return false; ids.add(x.event_id); return true;}); if(queue.length+fresh.length>10000) throw Error('Queue full (10,000 visits). Push or delete queued visits before collecting more.'); await api.storage.local.set({queue:queue.concat(fresh)}); }
async function flush() { const {config,queue=[]}=await api.storage.local.get(['config','queue']); if(!config?.token || !queue.length) return; const batch=queue.slice(0,100); const response=await fetch(config.server+'/api/history/visits',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+config.token},body:JSON.stringify({visits:batch}),credentials:'omit',redirect:'error',signal:AbortSignal.timeout(20000)}); if(!response.ok) throw Error('Push failed: HTTP '+response.status); const result=await response.json(); if(result.accepted!==batch.length) throw Error('Server did not acknowledge this batch'); await api.storage.local.set({queue:queue.slice(batch.length),lastError:'',lastSync:Date.now()}); }
async function guarded(fn) { try { await fn(); } catch(e) { await api.storage.local.set({lastError:e.message}); } }
// Each import step processes a time window. Dense windows are split to avoid search truncation.
async function importStep() { const {importState,config,queue=[]}=await api.storage.local.get(['importState','config','queue']); if(!importState?.windows?.length || !config?.enabled) return; if(queue.length>8000) return; const windows=importState.windows.slice(); const [start,end]=windows.pop(); const items=await api.history.search({text:'',startTime:start,endTime:end,maxResults:1000}); if(items.length>=1000) { if(end-start<=1) throw Error('Too many history entries in one millisecond; import stopped to avoid losing visits.'); const middle=Math.floor((start+end)/2); windows.push([start,middle],[middle,end]); } else { const visits=[]; for(const item of items) { if(!allowed(item.url,config)) continue; for(const visit of await api.history.getVisits({url:item.url})) if(visit.visitTime>=importState.start && visit.visitTime<=importState.end && visit.isLocal!==false) visits.push({event_id:'chrome:'+visit.visitId,url:item.url,title:(item.title||'').slice(0,1000),visited_at:new Date(visit.visitTime).toISOString()}); } await enqueue(visits); } await api.storage.local.set({importState:{start:importState.start,end:importState.end,windows,message:windows.length ? windows.length+' windows remaining' : 'Complete'}}); }
api.alarms.create('push',{periodInMinutes:1});
api.alarms.onAlarm.addListener(()=>locked(()=>guarded(async()=>{await flush(); if(api.history) await importStep();})));
if(api.history) api.history.onVisited.addListener(item=>locked(()=>guarded(async()=>{const visits=await api.history.getVisits({url:item.url}); await enqueue(visits.filter(v=>v.visitTime>=item.lastVisitTime && v.isLocal!==false).map(v=>({event_id:'chrome:'+v.visitId,url:item.url,title:(item.title||'').slice(0,1000),visited_at:new Date(v.visitTime).toISOString()})));})));
else api.tabs.onUpdated.addListener((id,change,tab)=>{ if(change.status==='complete' && !tab.incognito && tab.url) locked(()=>guarded(()=>enqueue([{event_id:'safari:'+crypto.randomUUID(),url:tab.url,title:(tab.title||'').slice(0,1000),visited_at:new Date().toISOString()}]))); });
api.runtime.onMessage.addListener((message,sender,respond)=>{ if(sender.id!==api.runtime.id) return; locked(async()=>{ if(message.type==='configure') { const {config}=await api.storage.local.get('config'); const next=message.config; if(config?.server!==next.server || config?.token!==next.token) await api.storage.local.set({queue:[],importState:null}); await api.storage.local.set({config:next,lastError:''}); } else if(message.type==='sync') await flush(); else if(message.type==='clear') await api.storage.local.set({queue:[],importState:null,lastError:''}); else if(message.type==='import') { if(!api.history) throw Error('Safari supports new visits only; existing history import requires Chrome.'); const {config}=await api.storage.local.get('config'); if(!config?.enabled) throw Error('Save settings and enable collection first.'); const end=Date.now(); await api.storage.local.set({importState:{start:end-30*86400000,end,windows:[[end-30*86400000,end]],message:'Started'}}); await importStep(); } return {ok:true}; }).then(respond,e=>{api.storage.local.set({lastError:e.message});respond({error:e.message});}); return true; });
